use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Action {
    MoveLeft,
    MoveDown,
    MoveUp,
    MoveRight,
    FocusLeft,
    FocusDown,
    FocusUp,
    FocusRight,
    Fullscreen,
    Center,
    LaunchTerminal,
    NextWorkspace,
    PreviousWorkspace,
    Workspace1,
    Workspace2,
    Workspace3,
    Workspace4,
    Workspace5,
    MoveToWorkspace1,
    MoveToWorkspace2,
    MoveToWorkspace3,
    MoveToWorkspace4,
    MoveToWorkspace5,
    LayoutLeftHalf,
    LayoutRightHalf,
    LayoutTopHalf,
    LayoutBottomHalf,
    LayoutMonocle,
    LayoutStacking,
    LayoutSplitH,
    LayoutSplitV,
    ToggleSplit,
    SplitHorizontal,
    SplitVertical,
    DetectWindow,
    Quit,
}

impl Action {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "move_left" => Some(Self::MoveLeft),
            "move_down" => Some(Self::MoveDown),
            "move_up" => Some(Self::MoveUp),
            "move_right" => Some(Self::MoveRight),
            "focus_left" => Some(Self::FocusLeft),
            "focus_down" => Some(Self::FocusDown),
            "focus_up" => Some(Self::FocusUp),
            "focus_right" => Some(Self::FocusRight),
            "fullscreen" => Some(Self::Fullscreen),
            "center" => Some(Self::Center),
            "launch_terminal" => Some(Self::LaunchTerminal),
            "next_workspace" => Some(Self::NextWorkspace),
            "previous_workspace" => Some(Self::PreviousWorkspace),
            "workspace_1" => Some(Self::Workspace1),
            "workspace_2" => Some(Self::Workspace2),
            "workspace_3" => Some(Self::Workspace3),
            "workspace_4" => Some(Self::Workspace4),
            "workspace_5" => Some(Self::Workspace5),
            "move_to_workspace_1" => Some(Self::MoveToWorkspace1),
            "move_to_workspace_2" => Some(Self::MoveToWorkspace2),
            "move_to_workspace_3" => Some(Self::MoveToWorkspace3),
            "move_to_workspace_4" => Some(Self::MoveToWorkspace4),
            "move_to_workspace_5" => Some(Self::MoveToWorkspace5),
            "layout_left_half" => Some(Self::LayoutLeftHalf),
            "layout_right_half" => Some(Self::LayoutRightHalf),
            "layout_top_half" => Some(Self::LayoutTopHalf),
            "layout_bottom_half" => Some(Self::LayoutBottomHalf),
            "layout_monocle" => Some(Self::LayoutMonocle),
            "layout_stacking" => Some(Self::LayoutStacking),
            "layout_split_h" => Some(Self::LayoutSplitH),
            "layout_split_v" => Some(Self::LayoutSplitV),
            "toggle_split" => Some(Self::ToggleSplit),
            "split_horizontal" => Some(Self::SplitHorizontal),
            "split_vertical" => Some(Self::SplitVertical),
            "detect_window" => Some(Self::DetectWindow),
            "quit" => Some(Self::Quit),
            _ => None,
        }
    }
}
